### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by piaoniao** [dengzii/WiFiADB#7]
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.base/java.util.Collections$SingletonList.get(Collections.java:4849)
	at com.dengzii.plugin.adb.utils.AdbUtils.getDeviceFromLine(AdbUtils.kt:217)
	at com.dengzii.plugin.adb.utils.AdbUtils.listDevice(AdbUtils.kt:80)
	at com.dengzii.plugin.adb.utils.AdbUtils.getConnectedDeviceList(AdbUtils.kt:62)
	at com.dengzii.plugin.adb.ui.AdbDialog.updateTableOnUi(AdbDialog.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dengzii** [comment]
你好, 能提供一下完整 log 吗
查看日志在 Main > Log
